Fixed gcc error message:
scsi.c:1047: warning: dereferencing 'void *' pointer
scsi.c:1047: error: void value not ignored as it ought to be

The reason is that scsireq_t->data has now (NetBSD 4.99.30) the type
void *, which seems to have been char * before.