converters/help2man: Fix rpath on lib/binddomain.so
Perhaps due to updated PKG_DEVELOPER checks, help2man begin to fail
during the install stage with this option set:

ERROR: lib/bindtextdomain.so: missing library: libintl.so.8

I checked the rpath definition of bindtextdomain; the only value was
provided by the system compiler.  The LD_CONFIG hint file on DragonFly
provides /usr/pkg/lib as late runtime search path option, so the
libintl.so library would get found anyway if help2man was installed
without PKG_DEVELOPER=yes set.

The updated patch-aa adds ${prefix}/lib to bindtextdomain.so rpath so
it will pass PKG_DEVELOPER checks now.