Update to 1.2:
* Version 1.2 (released 2007-10-01)

** Development git tree moved to savannah.
See <https://savannah.gnu.org/projects/libidn/>.

** Update gnulib files.
Including mono detection fixes.

** Update translations.

** API and ABI is backwards compatible with the previous version.

* Version 1.1 (released 2007-09-01)

** Fix compilation error in idn-int.h.
The error would typically be 'error: no include path in which to
search for stdint.h'.  Reported by Remko van der Vossen
<wich@stack.nl>, see
<http://thread.gmane.org/gmane.comp.gnu.libidn.general/65> and
<http://bugs.sourcemage.org/show_bug.cgi?id=13857>.

** Declare external variables with __declspec(import) for Windows.
Apparently this is required for variables in DLL's on Windows.  This
is enabled if __DECLSPEC_SUPPORTED is defined (MinGW), or if _MSC_VER
and_DLL is defined (MSVC).

** Update gnulib files.

** Update translations.

** API and ABI is backwards compatible with the previous version.