Reorder the linker tests in the configure script so that we test for C libraries *before* we throw the AC_LANG([C++]) switch.  This makes the generated configure script use the C compiler/linker instead of the C++ compiler/linker when running tests.  This avoids errors like these based on not correctly getting the function signature correct:
conftest.cc:36: error: nonnull argument with out-of-range operand
	number (arg 1, operand 2)

This error was causing the configure script to not detect *gettext()
routines and not building and installing the *.mo files.  This fixes
the error noted in the bulk build results:

    http://mail-index.netbsd.org/pkgsrc-bulk/2006/06/20/0000.html